name: Head branch workflow

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  test:
    uses: bgd-labs/github-workflows/.github/workflows/comment.yml@main
    secrets: inherit
